-- PUBLIC.CV02_ROLES definição
-- Drop table
-- DROP TABLE PUBLIC.CV02_ROLES;

CREATE TABLE PUBLIC.CV02_ROLES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DESCRICAO CHARACTER VARYING(255),
	NOME CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID),
	CONSTRAINT UKRCMFONWMMGU9ANNJ9LGOL61AE UNIQUE (NOME)
);

CREATE UNIQUE INDEX PRIMARY_KEY_3 ON
PUBLIC.CV02_ROLES (ID);

CREATE UNIQUE INDEX UKRCMFONWMMGU9ANNJ9LGOL61AE_INDEX_3 ON
PUBLIC.CV02_ROLES (NOME);
-- PUBLIC.CV01_USUARIOS definição
-- Drop table
-- DROP TABLE PUBLIC.CV01_USUARIOS;

CREATE TABLE PUBLIC.CV01_USUARIOS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ATIVO BOOLEAN NOT NULL,
	ATUALIZADO_EM TIMESTAMP,
	CPF CHARACTER VARYING(255) NOT NULL,
	CRIADO_EM TIMESTAMP NOT NULL,
	DATA_NASCIMENTO DATE,
	EMAIL CHARACTER VARYING(255) NOT NULL,
	NOME CHARACTER VARYING(255) NOT NULL,
	SENHA CHARACTER VARYING(255) NOT NULL,
	BIGINT_ROLE_ID BIGINT NOT NULL,
	CONSTRAINT CONSTRAINT_E PRIMARY KEY (ID),
	CONSTRAINT UK2LA2Y02LRQRS2XXWO5SEHIFM5 UNIQUE (EMAIL),
	CONSTRAINT UKMXHKBY5167S4T2Q6DKXBS9YJE UNIQUE (CPF),
	CONSTRAINT FK406KBYBS7XI6MD4B3C068CKN9 FOREIGN KEY (BIGINT_ROLE_ID) REFERENCES PUBLIC.CV02_ROLES(ID)
);

CREATE INDEX FK406KBYBS7XI6MD4B3C068CKN9_INDEX_E ON
PUBLIC.CV01_USUARIOS (BIGINT_ROLE_ID);

CREATE UNIQUE INDEX PRIMARY_KEY_E ON
PUBLIC.CV01_USUARIOS (ID);

CREATE UNIQUE INDEX UK2LA2Y02LRQRS2XXWO5SEHIFM5_INDEX_E ON
PUBLIC.CV01_USUARIOS (EMAIL);

CREATE UNIQUE INDEX UKMXHKBY5167S4T2Q6DKXBS9YJE_INDEX_E ON
PUBLIC.CV01_USUARIOS (CPF);
